server:
  port: 8088
spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
  application:
    name: API-Gateway
  cloud:
    gateway:
      # Load balanced via Eureka
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: subscription-service
              uri: lb://SUBSCRIPTION-SERVICE
              predicates:
                - Path=/subscription/**

eureka:
  client:
    service-url:
      defaultZone: ${local_eureka_server}
