spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${AUTH_DB_LOCAL_URL}
    username: ${AUTH_DB_LOCAL_USER}
    password: ${AUTH_DB_LOCAL_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      url: ${LOCAL_REDIS_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

email: ${EMAIL}
email_password: ${EMAIL_PASSWORD}

jwt_secret_key: ${JWT_SECRET_KEY}






